{
    'name': "SE Server Management",
    'version': '18.0.1.0.0',
    'author': "David Montero Crespo",
    'website': "https://github.com/keadanis/modulos_v18",
    'category': 'Tools',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        "security/ir.model.access.csv",
        "view/command_view.xml",
        "view/server_view.xml",
        "wizard/se_ssh_auth_view.xml",
        "data/ir_parameters.xml",
        "data/data.xml",
    ],
    'installable': True,
    'application': False,
    "images": ['static/description/server.png'],
}